In [1]:
import tensorflow as tf
print(f"TensorFlow {tf.__version__}")

TensorFlow 2.9.1


In [2]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

### Build a machine Learning Model

In [3]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28, 28)),
    tf.keras.layers.Dense(128, activation = 'relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10),
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.05457582,  0.4857572 ,  0.05671325,  0.11067773,  0.03711727,
        -0.73821115, -0.5435431 , -0.13403243,  0.9024847 ,  0.10171258]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.08385838, 0.14394946, 0.09373001, 0.09892707, 0.09191116,
        0.04232992, 0.05142694, 0.07745311, 0.21836978, 0.09804413]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

3.1622612

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [10]:
model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 [==============================] - 9s 3ms/step - loss: 0.2967 - accuracy: 0.9136
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1466 - accuracy: 0.9556
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1081 - accuracy: 0.9667
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0886 - accuracy: 0.9724
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0750 - accuracy: 0.9764


In [11]:
model.evaluate(x_test,  y_test, verbose=2)


313/313 - 1s - loss: 0.0804 - accuracy: 0.9754 - 970ms/epoch - 3ms/step


[0.08043697476387024, 0.9753999710083008]

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


In [13]:
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.93930185e-07, 2.10976623e-08, 7.03112964e-05, 3.34485143e-04,
        4.98715522e-12, 5.15923546e-07, 4.78576217e-13, 9.99592960e-01,
        5.94139351e-07, 6.87484601e-07],
       [4.05546929e-09, 2.55978899e-04, 9.99739468e-01, 4.31707622e-06,
        1.27317152e-15, 4.83922236e-08, 3.00830862e-08, 3.51064483e-10,
        2.09962224e-07, 1.63067480e-14],
       [5.08170714e-08, 9.99438465e-01, 7.67906895e-05, 8.17416549e-06,
        4.91244145e-06, 9.02009219e-07, 4.04323418e-06, 4.24013968e-04,
        4.26135121e-05, 7.62729542e-08],
       [9.99919891e-01, 1.15732768e-09, 5.63950471e-06, 1.12171726e-07,
        1.90412806e-07, 2.14152919e-06, 6.71987582e-05, 4.24187056e-06,
        6.55758292e-09, 4.64393821e-07],
       [5.00468668e-05, 4.34584386e-08, 8.01959250e-05, 1.08473770e-07,
        9.84334052e-01, 5.15921129e-05, 1.54619585e-04, 4.80015529e-03,
        1.07240185e-05, 1.05184289e-02]], dtype=float32)>